#!/us/bin/perl

my @start;

while (my $line = <>)
{
	if ($line =~ /^<x=([^,]+),\s*y=([^,]+),\s*z=([^,]+)>/)
	{
		push @start, [ $1, $2, $3, 0, 0, 0 ];
	}
}

my @moons = @start;
for (my $d = 0; $d < 3; $d++)
{
	my $steps = 0;
	while (1)
	{
		$steps++;
		# Update velocity using gravity
		for (my $i = 0; $i < (@moons - 1); $i++)
		{
			my $moon1 = $moons[$i];
			for (my $j = $i + 1; $j < @moons; $j++)
			{
				my $moon2 = $moons[$j];
				if ($moon1->[$d] < $moon2->[$d])
				{
					$moon1->[3 + $d]++;
					$moon2->[3 + $d]--;
				}
				elsif ($moon1->[$d] > $moon2->[$d])
				{
					$moon1->[3 + $d]--;
					$moon2->[3 + $d]++;
				}
			}
		}

		# Update position using velocity
		# Check for loop
		my $same = 0;
		for (my $i = 0; $i < @moons; $i++)
		{
			my $moon = $moons[$i];
			$moon->[$d] += $moon->[3 + $d];
			if (!$moon->[3 + $d] && ($moon->[$d] == $start[$i]->[$d]))
			{
				$same++;
			}
		}
		last if ($same == @moons);
	}
	printf("%d: loops after %d\n", $d, $steps);
}
