#!/usr/bin/perl

my $day = shift @ARGV;

my $params1 = shift @ARGV;
my $params2 = shift @ARGV;

print("Day $day:\n"); 

system("perl $day/day${day}_1 " . params($params1). " $day/input");
system("perl $day/day${day}_2 " . params($params2) . " $day/input");

exit(0);

sub params
{
	my ($p) = @_;

	return "" if (!defined $p);
	return "-i $p";
}
