#!/usr/bin/perl

use strict;
use integer;

my $fh;

die "* no input\n" if (!open($fh, '<', 'input.txt'));

my @list;
my @arr;

my $count = 0;

while (my $line = <$fh>)
{
	if ($line =~ /^(\d+)-(\d+) ([a-z]): ([a-z]+)/) {
		my ($min, $max, $letter, $password) = ($1, $2, $3, $4);
		my $num = () = $password =~ /$letter/g;
		$count++ if ($num >= $min && $num <= $max);
	}
}

printf("Answer: %d\n", $count);
