#!/usr/bin/perl

use strict;
use integer;

my $fh;

die "* no input\n" if (!open($fh, '<', $ARGV[0] || 'input.txt'));

my @list;
my @arr;

my $linenum = 0;
my $count = 0;

while (my $line = <$fh>)
{
	$linenum++;
	if ($line =~ /^(\d+)-(\d+) ([a-z]): ([a-z]+)/)
	{
		my ($a, $b, $letter, $password) = ($1, $2, $3, $4);
		my $c = substr($password, $a - 1, 1);
		my $d = substr($password, $b - 1, 1);
		$count++ if (($c eq $letter) != ($d eq $letter));
	}
}

printf("Answer: %d\n", $count);
