#!/usr/bin/perl

use strict;
use integer;

my ($from, $to) = split('-', <>);

printf("Count: %d\n", run_test($from, $to));

exit(0);

sub run_test
{
	my ($from, $to) = @_;

	my $count = 0;

	for (my $i = $from; $i <= $to; $i++)
	{
		next if ($i !~ /(.)\1/);
		next if ($i =~ /(10|2[10]|3[210]|4[3210]|5[43210]|6[543210]|7[6543210]|8[76543210]|9[876543210])/);
		$count++;
	}

	return $count;
}
