all: day1 day2 day3 day4 day5 day6 day7 day8 day9

.SILENT:

day1:
	../runday 1

day2:
	../runday 2

day3:
	../runday 3

day4:
	../runday 4

day5:
	../runday 5 1 5

day6:
	../runday 6

day7:
	../runday 7

day8:
	../runday 8

day9:
	../runday 9 1 2
