all: day1 day2 day3 day4 day5 day6 day7 day8 day9 day10 day11 day12 day13 day14 day15

.SILENT:

day1:
	../runday 1

day2:
	../runday 2

day3:
	../runday 3

day4:
	../runday 4

day5:
	../runday 5 1 5

day6:
	../runday 6

day7:
	../runday 7

day8:
	../runday 8

day9:
	../runday 9 1 2

day10:
	../runday 10

day11:
	../runday 11

day12:
	../runday 12

day13:
	../runday 13

day14:
	../runday 14

day15:
	../runday 15
