#!/usr/bin/perl

use strict;
use integer;

my $sum = 0;

$/ = undef; # slurp

my $input = <>;
$input =~ s/\s+//g;

my @input = split(",", $input);

run_test(\@input, 12, 2);

print("Answer: $input[0]\n");

exit(0);

sub run_test
{
	my ($mem, $noun, $verb) = @_;

	$mem->[1] = $noun;
	$mem->[2] = $verb;

	my $pc = 0;

	while (1)
	{
		my $opcode = $mem->[$pc];
		if ($opcode == 1)
		{
			my ($a, $b, $c) = @{$mem}[$pc+1 .. $pc+3];
			$mem->[$c] = $mem->[$a] + $mem->[$b];
			$pc += 4;
		}
		elsif ($opcode == 2)
		{
			my ($a, $b, $c) = @{$mem}[$pc+1..$pc+3];
			$mem->[$c] = $mem->[$a] * $mem->[$b];
			$pc += 4;
		}
		elsif ($opcode == 99)
		{
			#print("Program terminated at $pc\n");
			last;
		}
		else
		{
			print("Invalid opcode $opcode at position $pc\n");
			last;
		}
	}
}
